#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
  # Configure loopback and lan
  echo "config interface 'loopback'
    option ifname 'lo'
    option proto 'static'
    option ipaddr '127.0.0.1'
    option netmask '255.0.0.0'

config interface 'lan'
    option type 'bridge'
    option ifname 'eth0'
    option proto 'static'
    option ipaddr '$UU_LAN_IPADDR'
    option gateway '$UU_LAN_GATEWAY'
    option netmask '$UU_LAN_NETMASK'
    list dns '$UU_LAN_DNS'" > /etc/config/network

  # Restart network to apply changes
  /etc/init.d/network restart

  # Configure DHCP and DNS
  uci set dhcp.lan.ignore=1
  uci commit dhcp
  /etc/init.d/dnsmasq restart

  # Prepare environment
  rm -rf /tmp/uu && mkdir -p /tmp/uu

  procd_open_instance
  procd_set_param command /usr/local/sbin/uuplugin /etc/uu.conf
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_set_param respawn
  procd_close_instance
  
  # Forward syslog to Docker logs (wait for logd to be ready)
  ( sleep 5 && logread -f > /proc/1/fd/1 2>&1 ) &
}
