#!/bin/sh /etc/rc.common

START=99

start() {
  # Configure loopback and lan
  echo "config interface 'loopback'
    option ifname 'lo'
    option proto 'static'
    option ipaddr '127.0.0.1'
    option netmask '255.0.0.0'

config interface 'lan'
    option type 'bridge'
    option ifname 'eth0'
    option proto 'static'
    option ipaddr '$UU_LAN_IPADDR'
    option gateway '$UU_LAN_GATEWAY'
    option netmask '$UU_LAN_NETMASK'
    list dns '$UU_LAN_DNS'" > /etc/config/network

  # Restart network to apply changes
  /etc/init.d/network restart

  # Configure DHCP and DNS
  uci set dhcp.lan.ignore=1
  uci commit dhcp
  /etc/init.d/dnsmasq restart

  # Prepare environment
  rm -rf /tmp/uu && mkdir -p /tmp/uu

  echo "Starting uuplugin (output to /dev/console)..." > /dev/console
  # Start uuplugin in background and redirect output to /dev/console
  /usr/local/sbin/uuplugin /etc/uu.conf > /dev/console 2>&1 &
}
